INSERT INTO visibility_report_requests (email, domain, score, status, metadata) VALUES
('chris.abouraad@smbteam.com', 'lawofficeofpollytatum.com', 0, 'pending', '{"firstName": "Polly"}'::jsonb),
('chris.abouraad@smbteam.com', 'inkellfirm.com', 0, 'pending', '{"firstName": "Josh"}'::jsonb),
('chris.abouraad@smbteam.com', 'justletjoeknow.com', 0, 'pending', '{"firstName": "Joseph"}'::jsonb),
('chris.abouraad@smbteam.com', 'millerelderlawfirm.com', 0, 'pending', '{"firstName": "Zachary"}'::jsonb),
('chris.abouraad@smbteam.com', 'ateaselaw.com', 0, 'pending', '{"firstName": "Melissa"}'::jsonb),
('chris.abouraad@smbteam.com', 'andresmejerlaw.com', 0, 'pending', '{"firstName": "Andres"}'::jsonb),
('chris.abouraad@smbteam.com', 'mclellanlawgroup.com', 0, 'pending', '{"firstName": "Claire"}'::jsonb),
('chris.abouraad@smbteam.com', 'burnhamdouglass.com', 0, 'pending', '{"firstName": "Philip"}'::jsonb),
('chris.abouraad@smbteam.com', 'caresslaw.estate', 0, 'pending', '{"firstName": "Tammi"}'::jsonb),
('chris.abouraad@smbteam.com', 'taylorwray.ca', 0, 'pending', '{"firstName": "Jordan"}'::jsonb),
('chris.abouraad@smbteam.com', 'lannenlawpllc.com', 0, 'pending', '{"firstName": "Brittany"}'::jsonb),
('chris.abouraad@smbteam.com', 'chapmanstender.com', 0, 'pending', '{"firstName": "Kyle"}'::jsonb),
('chris.abouraad@smbteam.com', 'leinartlaw.com', 0, 'pending', '{"firstName": "Christi"}'::jsonb),
('chris.abouraad@smbteam.com', 'jalawgroup.com', 0, 'pending', '{"firstName": "Julia"}'::jsonb),
('chris.abouraad@smbteam.com', 'tyrelawgroup.com', 0, 'pending', '{"firstName": "Tony"}'::jsonb),
('chris.abouraad@smbteam.com', 'drurypullenlaw.com', 0, 'pending', '{"firstName": "Susanna"}'::jsonb),
('chris.abouraad@smbteam.com', '855getjjlaw.com', 0, 'pending', '{"firstName": "Jonathan"}'::jsonb),
('chris.abouraad@smbteam.com', 'themonarchlawgroup.com', 0, 'pending', '{"firstName": "Sara"}'::jsonb),
('chris.abouraad@smbteam.com', 'immigrationforcouples.com', 0, 'pending', '{"firstName": "Megan"}'::jsonb),
('chris.abouraad@smbteam.com', 'accident-attorneys.com', 0, 'pending', '{"firstName": "Tracee"}'::jsonb),
('chris.abouraad@smbteam.com', 'justjuirstlawfirm.com', 0, 'pending', '{"firstName": "Pablo"}'::jsonb),
('chris.abouraad@smbteam.com', 'gilmanlawpllc.net', 0, 'pending', '{"firstName": "Derek"}'::jsonb),
('chris.abouraad@smbteam.com', 'thegrandelawfirm.com', 0, 'pending', '{"firstName": "Cynthia"}'::jsonb),
('chris.abouraad@smbteam.com', 'provenlaw.com', 0, 'pending', '{"firstName": "E Lawrence"}'::jsonb),
('chris.abouraad@smbteam.com', 'smithelaw.com', 0, 'pending', '{"firstName": "Eon"}'::jsonb),
('chris.abouraad@smbteam.com', 'berenjifamilylaw.com', 0, 'pending', '{"firstName": "Nikoo"}'::jsonb);